# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jaka_k1_arm_l_controller
    - jaka_k1_arm_r_controller
    - jaka_k1_full_robot_controller

  jaka_k1_arm_l_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rb1_j1
      - rb1_j2
      - rb1_j3
      - rb1_j4
      - rb1_j5
      - rb1_j6
      - rb1_j7
  jaka_k1_arm_r_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rb2_j1
      - rb2_j2
      - rb2_j3
      - rb2_j4
      - rb2_j5
      - rb2_j6
      - rb2_j7
  jaka_k1_full_robot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rb1_j1
      - rb1_j2
      - rb1_j3
      - rb1_j4
      - rb1_j5
      - rb1_j6
      - rb1_j7
      - rb2_j1
      - rb2_j2
      - rb2_j3
      - rb2_j4
      - rb2_j5
      - rb2_j6
      - rb2_j7